--- 
abstract: Simple DOM parser for Makefiles
author: Agent Zhang <agentzh@gmail.com>
build_requires: 
  Test::Base: 0.53
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Makefile-DOM
no_index: 
  directory: 
    - inc
    - t
requires: 
  Clone: 0.18
  List::MoreUtils: 0.21
  Params::Util: 0.22
  perl: 5.6.1
tests: t/mdom/*.t t/mdom/*/*.t
version: 0.002
